import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { AgentCard, AgentIcon, BrandLockup, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, DashboardIcon, FlytrapIcon, InsightCallout, KpiStatCard, MessageBubble, PlaygroundIcon, SendIcon, ThemeDarkIcon, ThemeLightIcon } from "@flytrap/ui";
import "@flytrap/ui/styles";

const activity = [44, 61, 54, 78, 68, 89, 83, 96, 72, 91, 100, 87];

function App() {
  const [dark, setDark] = useState(false);
  return <div className={dark ? "dark" : ""}><div className="min-h-screen bg-background text-foreground lg:grid lg:grid-cols-[224px_1fr]">
    <aside className="border-b bg-sidebar p-5 lg:sticky lg:top-0 lg:h-screen lg:border-b-0 lg:border-r"><BrandLockup descriptor="Dashboard" /><nav className="mt-8 grid gap-1 text-sm"><a className="flex items-center gap-3 rounded-md bg-sidebar-accent px-3 py-2 font-medium" href="#dashboard"><FlytrapIcon icon={DashboardIcon} />Dashboard</a><a className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-sidebar-accent" href="#agents"><FlytrapIcon icon={AgentIcon} />Agents</a><a className="flex items-center gap-3 rounded-md px-3 py-2 font-medium hover:bg-sidebar-accent" href="#playground"><FlytrapIcon icon={PlaygroundIcon} />Playground</a></nav></aside>
    <main className="min-w-0 p-5 md:p-8"><header className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Design system analytics</p><h1 className="font-display text-2xl font-bold">Visão geral</h1></div><Button variant="outline" size="icon" aria-label="Alternar tema" onClick={() => setDark(value => !value)}><FlytrapIcon icon={dark ? ThemeLightIcon : ThemeDarkIcon} /></Button></header>
      <section id="dashboard" className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiStatCard label="Token adoption" value="87%" delta={12} description="no período" /><KpiStatCard label="APCA compliance" value="100%" delta={0} description="54 pares" /><KpiStatCard label="Módulos públicos" value="39" delta={30} description="na release 0.3" /><KpiStatCard label="Hardcoded values" value="14" delta={-18} description="no período" /></section>
      <section className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Card><CardHeader><CardTitle>Adoção semanal</CardTitle><CardDescription>Uso de tokens semânticos nos produtos.</CardDescription></CardHeader><CardContent><div className="flex h-56 items-end gap-2">{activity.map((value, index) => <div key={index} className="group relative flex-1 rounded-t-md bg-primary/20 transition-colors hover:bg-primary" style={{ height: `${value}%` }}><span className="sr-only">{value}%</span></div>)}</div></CardContent></Card><InsightCallout title="Sinal da semana" severity="success" className="h-fit">A adoção subiu 12%. O maior ganho veio da substituição de cores fixas pelos tokens de superfície e feedback.</InsightCallout></section>
      <section id="agents" className="mt-10"><h2 className="font-display text-xl font-bold">Agents</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><AgentCard name="Token validator" status="running" model="Claude Sonnet" tokens="2.3K">Validando contratos semânticos e pares APCA.</AgentCard><AgentCard name="Migration agent" status="completed" model="Claude Sonnet" tokens="890">Migração inicial para React concluída.</AgentCard><AgentCard name="Docs agent" status="idle" model="Claude Haiku">Aguardando novos componentes.</AgentCard></div></section>
      <section id="playground" className="mt-10"><h2 className="font-display text-xl font-bold">AI playground</h2><Card className="mt-4 max-w-3xl"><CardHeader><CardTitle>Converse com o design system</CardTitle><CardDescription>Interface preparada para a Edge Function `ai-chat`.</CardDescription></CardHeader><CardContent className="grid gap-3"><MessageBubble role="user">Qual token devo usar para uma ação primária?</MessageBubble><MessageBubble role="assistant">Use o token semântico <code>--primary</code>. O componente Button já consome esse contrato e acompanha brand, mode e theme.</MessageBubble><form className="mt-3 flex gap-2" onSubmit={event => event.preventDefault()}><input aria-label="Mensagem" placeholder="Pergunte sobre tokens e componentes…" className="h-10 flex-1 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /><Button size="icon" aria-label="Enviar"><FlytrapIcon icon={SendIcon} /></Button></form></CardContent></Card></section>
    </main>
  </div></div>;
}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
